env:
  rcloneconfig: "ENCRYPTED[26beb64227d1373eddf7f40e0184804cc813b1ff2aabf013714fc9857f692c39590d4594c51b211fcf3f4cad4fa5b094]"
  TG_TOKEN: "ENCRYPTED[b8dfc1a2afcd8c603b9dd7692b763c81c32aaa87b4b1f99428de1c14a66791b63f3c247c53e69542e36aba2822a87112]"
  TG_CHAT_ID: "ENCRYPTED[395f1b6b15ac31ef4446ae986a1f295e0f7565be314cfaf1c2847b7933a020f8bbe111694fb12215726f3af0d9819896]"
  WORKDIR: "/"
  EMAIL: "najmulhasan3609@gmail.com"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'nhAsif'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:21.10
    cpu: 8
    memory: 32G

  Environment-Check_background_script:
     - cat /etc/os* && env && nproc && gcc --version && clang --version
  
  Load-Ccache_background_script:
     - cd $WORKDIR
     - mkdir -p ~/.config/rclone
     - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
     - name_rom=$(grep init $CIRRUS_WORKING_DIR/build.sh -m 1 | cut -d / -f 4)
     - rclone copy --drive-chunk-size 256M --stats 1s gdrive:ccache/$name_rom/ccache.tar.gz $WORKDIR -P
     - tar xzf ccache.tar.gz
     - rm -rf ccache.tar.gz

  Storage-Check_background_script:
     - df -h && lsblk && ls -l -a -h
     
  Sync-rom_script:
     - set -exv
     - git config --global user.name $CIRRUS_REPO_OWNER
     - git config --global user.email $EMAIL
     - name_rom=$(grep init $CIRRUS_WORKING_DIR/build.sh -m 1 | cut -d / -f 4)
     - mkdir -p $WORKDIR/rom/$name_rom
     - cd $WORKDIR/rom/$name_rom
     - rm -rf .repo/local_manifests
     - command=$(head $CIRRUS_WORKING_DIR/build.sh -n $(expr $(grep 'build/envsetup.sh' $CIRRUS_WORKING_DIR/build.sh -n | cut -f1 -d:) - 1))
     - only_sync=$(grep 'repo sync' $CIRRUS_WORKING_DIR/build.sh)
     - bash -c "$command" || true
     - curl -sO https://api.cirrus-ci.com/v1/task/$CIRRUS_TASK_ID/logs/Sync-rom.log
     - a=$(grep 'Cannot remove project' Sync-rom.log -m1|| true)
     - b=$(grep "^fatal: remove-project element specifies non-existent project" Sync-rom.log -m1 || true)
     - c=$(grep 'repo sync has finished' Sync-rom.log -m1 || true)
     - d=$(grep 'Failing repos:' Sync-rom.log -n -m1 || true)
     - e=$(grep 'fatal: Unable' Sync-rom.log || true)
     - if [[ $a == *'Cannot remove project'* ]]
     - then
     - a=$(echo $a | cut -d ':' -f2)
     - rm -rf $a
     - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
     - elif [[ $b == *'remove-project element specifies non-existent'* ]]
     - then exit 1
     - elif [[ $c == *'repo sync has finished'* ]]
     - then true
     - elif [[ $d == *'Failing repos:'* ]]
     - then
     - d=$(expr $(grep 'Failing repos:' Sync-rom.log -n -m 1| cut -d ':' -f1) + 1)
     - d2=$(expr $(grep 'Try re-running' Sync-rom.log -n -m1 | cut -d ':' -f1) - 1 )
     - rm -rf $(head -n $d2 Sync-rom.log | tail -n +$d)
     - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
     - elif [[ $e == *'fatal: Unable'* ]]
     - then
     - rm -rf $(grep 'fatal: Unable' Sync-rom.log | cut -d ':' -f2 | cut -d "'" -f2)
     - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
     - else
     #- (repo forall -c 'git checkout .' && bash -c "$only_sync") || (find -name shallow.lock -delete && find -name index.lock -delete && bash -c "$only_sync")
     - exit 1
     - fi
     - rm -rf Sync-rom.log
     
  Build-rom_script:
     - set -e
     - name_rom=$(grep init $CIRRUS_WORKING_DIR/build.sh -m 1 | cut -d / -f 4)
     - device=$(grep unch $CIRRUS_WORKING_DIR/build.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
     - cd $WORKDIR/rom/$name_rom
     - export ALLOW_MISSING_DEPENDENCIES=true
     - export PATH="/usr/lib/ccache:$PATH"
     - export CCACHE_DIR=$WORKDIR/ccache
     - export CCACHE_EXEC=/usr/bin/ccache
     - export USE_CCACHE=1
     - export CCACHE_COMPRESS=true
     - export CCACHE_COMPRESSLEVEL=1
     - export CCACHE_LIMIT_MULTIPLE=0.9
     - which ccache
     - export CCACHE_MAXSIZE=50G
     - ccache -z
     - command=$(tail $CIRRUS_WORKING_DIR/build.sh -n +$(expr $(grep 'build/envsetup.sh' $CIRRUS_WORKING_DIR/build.sh -n | cut -f1 -d:) - 1)| head -n -1 | grep -v '# upload rom')
     - bash -c "$command" 

  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./ziping.sh
